export const SocketConstants = {
	Events: {
		AUTHENTICATE: "authenticate",
		AUTHENTICATE_FAILED: "authenticate_failed",
		SOCKET_READY: "socket_ready",
		REQUEST_AUTHENTICATION: "request_authentication",
		MESSAGE: "message",
		JOIN_ROOM: "join_room",
		JOINED_ROOM: "joined_room",
		FETCH_MESSAGES: "fetch_messages",
		EDIT_MESSAGE: "edit_message",
		DELETE_MESSAGE: "delete_message",
		MESSAGE_NOTIFICATION: "message_notification",
		FETCH_DIRECT_MESSAGES: "fetch_direct_messages",
		SEND_DIRECT_MESSAGE: "send_direct_message",
		DIRECT_MESSAGE: "direct_message",
		EDIT_DIRECT_MESSAGE: "edit_direct_message",
		DELETE_DIRECT_MESSAGE: "delete_direct_message",
		NOTIFICATION: "notification",
	},
};
