export const DbConstants = {
	TableName: {
		User: "user",
		Subscription: "subscription",
		GroupSubscription: "group_subscription",
		ShareFund: "share_fund",
		Transaction: "transaction",
		Message: "message",
		Group: "group",
		UserMessageDelete: "user_message_delete",
		PasswordResetToken: "password_reset_token",
		Attachment: "attachment",
		Channel: "channel",
		Thread: "thread",
		UserGroup: "user_group",
		AdminRole: "admin_role",
		Permission: "permission",
		UserFriend: "user_friend",
		AuditLog: "audit_log",
		Task: "task",
		TaskHistory: "task_history",
		Todo: "todo",
		CodeBlock: "code_block",
		DirectMessage: "direct_message",
		FriendRequest: "friend_request",
		GroupInvitation: "group_invitation",
		Notification: "notification",
		AiSession: "ai_session",
		AiInteraction: "ai_interaction",
		CodeCollaboration: "code_collaboration",
		ThreadMessage: "thread_message",
		SupportedProgrammingLanguage: "supported_programming_language",
		GroupSupportedProgrammingLanguage: "group_supported_programming_language",
		UserLanguageCollection: "user_language_collection",
		ReportCategory: "report_category",
		Report: "report",
		ReportReportCategory: "report_report_category",
		RunCodeCache: "run_code_cache",
	},
	ColumnName: {
		User: {
			id: "user_id",
			username: "username",
			email: "email",
			password: "password",
			firstName: "first_name",
			lastName: "last_name",
			avatarUrl: "avatar_url",
			isActive: "is_active",
			banReason: "ban_reason",
			emailVerified: "email_verified",
			emailVerificationToken: "email_verification_token",
			emailVerifiedAt: "email_verified_at",
			createdAt: "created_at",
			updatedAt: "updated_at",
			lastLogin: "last_login",
			timezone: "timezone",
			adminRoleId: "admin_role_id",
			isAdmin: "is_admin",
			isBot: "is_bot",
			subscriptionRole: "subscription_role",
		},
		Message: {
			id: "message_id",
			senderId: "sender_id",
			content: "content",
			parentMessageId: "parent_message_id",
			isFirstThreadMessage: "is_first_thread_message",
		},
		UserMessageDelete: {
			id: "user_message_delete_id",
			userId: "user_id",
			messageId: "message_id",
		},
		PasswordResetToken: {
			id: "password_reset_token_id",
			userId: "user_id",
			verifyCode: "verify_code",
			expiresAt: "expires_at",
			usedAt: "used_at",
			attempts: "attempts",
		},
		Attachment: {
			id: "attachment_id",
			messageId: "message_id",
			fileName: "file_name",
			originalFileName: "original_file_name",
			filePath: "file_path",
			fileSize: "file_size",
			fileType: "file_type",
			folder: "folder",
			format: "format",
			publicId: "public_id",
			uploadedBy: "uploaded_by",
			channelId: "channel_id",
			toUserId: "to_user_id",
		},
		Audit: {
			createdAt: "created_at",
			updatedAt: "updated_at",
			deletedAt: "deleted_at",
			createdBy: "created_by",
			updatedBy: "updated_by",
			deletedBy: "deleted_by",
			isActive: "is_active",
		},
		Group: {
			id: "group_id",
			name: "name",
			description: "description",
			avatar: "avatar",
			createdBy: "created_by",
			createdAt: "created_at",
			updatedAt: "updated_at",
			isActive: "is_active",
		},
		Channel: {
			id: "channel_id",
			name: "channel_name",
			description: "channel_description",
		},
		Thread: {
			id: "thread_id",
			name: "thread_name",
			description: "thread_description",
		},
		UserGroup: {
			id: "user_group_id",
			userId: "user_id",
			groupId: "group_id",
			addedBy: "added_by",
			joinedAt: "joined_at",
			invitedAt: "invited_at",
			status: "status",
			acceptedAt: "accepted_at",
		},
		AdminRole: {
			id: "admin_role_id",
			role: "role",
			roleName: "role_name",
			roleLevel: "role_level",
			permissions: "permissions",
		},
		Permission: {
			id: "permission_id",
			code: "permission_code",
			name: "permission_name",
			description: "permission_description",
		},
		UserFriend: {
			id: "user_friend_id",
			userId: "user_id",
			friendId: "friend_id",
		},
		AuditLog: {
			id: "audit_log_id",
			userId: "user_id",
			action: "action",
			entityType: "entity_type",
			oldValues: "old_values",
			newValues: "new_values",
		},
		Task: {
			id: "task_id",
			name: "name",
			description: "description",
			status: "status",
			priority: "priority",
			startDate: "start_date",
			dueDate: "due_date",
			assigneeId: "assignee_id",
		},
		TaskHistory: {
			id: "task_history_id",
			taskId: "task_id",
			userId: "user_id",
			action: "action",
			fieldName: "field_name",
			oldValue: "old_value",
			newValue: "new_value",
		},
		Todo: {
			id: "todo_id",
			name: "name",
			description: "description",
			priority: "priority",
			status: "status",
			dueDate: "due_date",
		},
		CodeBlock: {
			id: "code_block_id",
			userId: "user_id",
			title: "title",
			description: "description",
			language: "language",
			content: "content",
			executionResult: "execution_result",
			executionStatus: "execution_status",
			executedAt: "executed_at",
			channelId: "channel_id",
			toUserId: "to_user_id",
		},
		DirectMessage: {
			id: "direct_message_id",
			fromUserId: "from_user_id",
			toUserId: "to_user_id",
			content: "content",
			parentMessageId: "parent_message_id",
		},
		FriendRequest: {
			id: "friend_request_id",
			fromUserId: "from_user_id",
			toUserId: "to_user_id",
			status: "status",
			message: "message",
		},
		GroupInvitation: {
			id: "group_invitation_id",
			fromUserId: "from_user_id",
			toUserId: "to_user_id",
			groupId: "group_id",
			status: "status",
			message: "message",
		},
		Notification: {
			id: "notification_id",
			toUserId: "to_user_id",
			title: "notification_title",
			content: "notification_content",
			notificationSource: "notification_source",
			isRead: "is_read",
		},
		AiSession: {
			id: "ai_session_id",
			userId: "user_id",
			channelId: "channel_id",
			threadId: "thread_id",
			sessionType: "session_type",
			startedAt: "started_at",
			endedAt: "ended_at",
			status: "status",
		},
		AiInteraction: {
			id: "ai_interaction_id",
			sessionId: "ai_session_id",
			userId: "user_id",
			messageId: "message_id",
			aiResponse: "ai_response",
			model: "ai_model",
			contextData: "context_data",
			responseTime: "response_time",
		},
		CodeCollaboration: {
			id: "code_collaboration_id",
			content: "content",
		},
		ThreadMessage: {
			id: "thread_message_id",
			content: "content",
			senderId: "sender_id",
			parentMessageId: "parent_message_id",
		},
		SupportedProgrammingLanguage: {
			id: "supported_programming_language_id",
			languageCode: "language_code",
			languageName: "language_name",
			languageIcon: "language_icon",
			languageVersion: "language_version",
			isExecutable: "is_executable",
			preset: "preset",
			useAiCheck: "use_ai_check",
		},
		GroupSupportedProgrammingLanguage: {
			id: "group_supported_programming_language_id",
			groupId: "group_id",
			supportedProgrammingLanguageId: "supported_programming_language_id",
		},
		UserLanguageCollection: {
			id: "user_language_collection_id",
			userId: "user_id",
			languageId: "language_id",
			proficiencyLevel: "proficiency_level",
			orderIndex: "order_index",
		},
		ReportCategory: {
			id: "report_category_id",
			name: "name",
			description: "description",
			isRemoved: "is_removed",
		},
		Report: {
			id: "report_id",
			content: "content",
			messageType: "message_type",
		},
		ReportReportCategory: {
			id: "report_report_category_id",
		},
		RunCodeCache: {
			id: "run_code_cache_id",
			targetId: "target_id",
			runCodeType: "run_code_type",
			result: "result",
		},
		Subscription: {
			id: "subscription_id",
			subscriptionCode: "subscription_code",
			subcriptionName: "subscription_name",
			price: "price",
			limitMembers: "limit_members",
			isAIActive: "is_ai_active",
			runCodePerDay: "run_code_per_day",
			programmingLanguageInGroups: "programming_language_in_groups",
			allowUseAI: "allow_use_ai",
			levelSubscription: "level_subscription",
		},
		GroupSubscription: {
			id: "group_subscription_id",
			groupId: "group_id",
			subscriptionId: "subscription_id",
			groupSubscriptionStatus: "group_subscription_status",
			monthQuantity: "month_quantity",
			payemntBy: "payment_by",
			isPaid: "is_paid",
			startedAt: "started_at",
			endedAt: "ended_at",
		},
		ShareFund: {
			id: "share_fund_id",
			groupId: "group_id",
			subscriptionId: "subscription_id",
			monthQuantity: "month_quantity",
			fundName: "fund_name",
			contributeTime: "contribute_time",
			currentVndAmount: "current_vnd_amount",
			createdAt: "created_at",
			updatedAt: "updated_at",
		},
		Transaction: {
			id: "transaction_id",
			vndAmount: "vnd_amount",
			transactionMessage: "transaction_message",
			paymentMethod: "payment_method",
			transactionStatus: "transaction_status",
			transactionType: "transaction_type",
			transactionCode: "transaction_code",
			userId: "user_id",
			groupSubscriptionId: "group_subscription_id",
			shareFundId: "share_fund_id",
			groupId: "group_id",
			subscriptionId: "subscription_id",
		},
	},
	IndexName: {
		User: {
			username: "idx_user_unique_username",
			email: "idx_user_unique_email",
		},
		Group: {
			name: "idx_group_name",
		},
		Channel: {
			name: "idx_channel_unique_name",
			groupId: "idx_channel_normal_group",
		},
		PasswordResetToken: {
			userId: "idx_password_reset_token_normal_userId",
			verifyCode: "idx_password_reset_token_normal_verifyCode",
		},
		Attachment: {
			messageId: "idx_attachment_normal_messageId",
		},
		AuditLog: {
			userId: "idx_audit_log_normal_userId",
			entityType: "idx_audit_log_normal_entityType",
			entityId: "idx_audit_log_normal_entityId",
		},
		Task: {
			groupId: "idx_task_normal_groupId",
		},
		Todo: {
			userId: "idx_todo_normal_userId",
		},
		Notification: {
			userId: "idx_notification_normal_toUserId",
		},
		AiSession: {
			userId: "idx_ai_session_normal_userId",
			channelId: "idx_ai_session_normal_channelId",
			threadId: "idx_ai_session_normal_threadId",
			status: "idx_ai_session_normal_status",
		},
		AiInteraction: {
			sessionId: "idx_ai_interaction_normal_sessionId",
			userId: "idx_ai_interaction_normal_userId",
			messageId: "idx_ai_interaction_normal_messageId",
		},
		RunCodeCache: {
			typeAndTarget: "idx_run_code_cache_type_and_target",
		},
		GroupSubscription: {
			groupId: "idx_group_subscription_group_id",
			subscriptionId: "idx_group_subscription_subscription_id",
		},
		ShareFund: {
			groupId: "idx_share_fund_group_id",
			subscriptionId: "idx_share_fund_subscription_id",
		},
		Transaction: {
			userId: "idx_transaction_user_id",
			groupId: "idx_transaction_group_id",
			shareFundId: "idx_transaction_share_fund_id",
		},
	},
};
