export const DbConstants = {
	TableName: {
		User: "user",
		Message: "message",
		Group: "group",
		UserMessageDelete: "user_message_delete",
		PasswordResetToken: "password_reset_token",
		Attachment: "attachment",
	},
	ColumnName: {
		User: {
			id: "user_id",
			username: "username",
			email: "email",
			password: "password",
			firstName: "first_name",
			lastName: "last_name",
			avatarUrl: "avatar_url",
			isActive: "is_active",
			emailVerified: "email_verified",
			emailVerificationToken: "email_verification_token",
			createdAt: "created_at",
			updatedAt: "updated_at",
			lastLogin: "last_login",
			timezone: "timezone",
		},
		Message: {
			id: "message_id",
			channelId: "channel_id",
			threadId: "thread_id",
			senderId: "sender_id",
			content: "content",
			parentMessageId: "parent_message_id",
		},
		UserMessageDelete: {
			id: "user_message_delete_id",
			userId: "user_id",
			messageId: "message_id",
		},
		PasswordResetToken: {
			id: "password_reset_token_id",
			userId: "user_id",
			code: "code",
			expiresAt: "expires_at",
			usedAt: "used_at",
			attempts: "attempts",
		},
		Attachment: {
			id: "attachment_id",
			messageId: "message_id",
			fileName: "file_name",
			originalFileName: "original_file_name",
			filePath: "file_path",
			fileSize: "file_size",
			fileType: "file_type",
			folder: "folder",
			format: "format",
			publicId: "public_id",
			uploadedBy: "uploaded_by",
		},
		Audit: {
			createdAt: "created_at",
			updatedAt: "updated_at",
			deletedAt: "deleted_at",
		},
		Group: {
			id: "group_id",
			name: "name",
			description: "description",
			avatar: "avatar",
			createdBy: "created_by",
			createdAt: "created_at",
			updatedAt: "updated_at",
			isActive: "is_active",
		},
	},
	IndexName: {
		User: {
			username: "idx_user_unique_username",
			email: "idx_user_unique_email",
		},
		Group: {
			name: "idx_group_name",
		},
		PasswordResetToken: {
			userId: "idx_password_reset_user",
			code: "idx_password_reset_code",
		},
		Attachment: {
			messageId: "idx_attachment_message",
		},
	},
};
