import { Global, Module } from "@nestjs/common";
import { TypeOrmModule } from "@nestjs/typeorm";
import { datasource } from "./datasource";
import { addTransactionalDataSource } from "typeorm-transactional";
import {
	UserRepository,
	MessageRepository,
	UserMessageDeleteRepository,
	PasswordResetTokenRepository,
	AttachmentRepository,
	UserGroupRepository,
	ChannelRepository,
	ThreadRepository,
	GroupRepository,
	PermissionRepository,
	UserFriendRepository,
	AuditLogRepository,
	TaskRepository,
	TaskHistoryRepository,
	TodoRepository,
	CodeBlockRepository,
	DirectMessageRepository,
	FriendRequestRepository,
	GroupInvitationRepository,
	NotificationRepository,
	AiSessionRepository,
	AiInteractionRepository,
	CodeCollaborationRepository,
	ThreadMessageRepository,
	SupportedProgrammingLanguageRepository,
	GroupSupportedProgrammingLanguageRepository,
	UserLanguageCollectionRepository,
	ReportCategoryRepository,
	ReportRepository,
	ReportReportCategoryRepository,
	RunCodeCacheRepostiroy,
	SubscriptionRepository,
	GroupSubscriptionRepository,
	ShareFundRepository,
	TransactionRepository,
} from "./repositories";

const repositories = [
	UserRepository,
	MessageRepository,
	GroupRepository,
	UserMessageDeleteRepository,
	PasswordResetTokenRepository,
	AttachmentRepository,
	UserGroupRepository,
	ChannelRepository,
	ThreadRepository,
	PermissionRepository,
	UserFriendRepository,
	AuditLogRepository,
	TaskRepository,
	TaskHistoryRepository,
	TodoRepository,
	CodeBlockRepository,
	DirectMessageRepository,
	FriendRequestRepository,
	GroupInvitationRepository,
	NotificationRepository,
	AiSessionRepository,
	AiInteractionRepository,
	CodeCollaborationRepository,
	ThreadMessageRepository,
	SupportedProgrammingLanguageRepository,
	GroupSupportedProgrammingLanguageRepository,
	UserLanguageCollectionRepository,
	ReportCategoryRepository,
	ReportRepository,
	ReportReportCategoryRepository,
	RunCodeCacheRepostiroy,
	SubscriptionRepository,
	GroupSubscriptionRepository,
	ShareFundRepository,
	TransactionRepository,
];

@Module({
	imports: [
		TypeOrmModule.forRootAsync({
			useFactory: () => datasource.options,
			dataSourceFactory: async () => addTransactionalDataSource(datasource),
		}),
	],
	providers: [...repositories],
	exports: [...repositories],
})
@Global()
export class DbModule {}
