sequenceDiagram
    autonumber
    User->>DevChat Web: Request Login
    DevChat Web->>Google/GitHub Login: Redirect
    Google/GitHub Login->>DevChat Web: Authorization code
    DevChat Web->>DevChat API: Authorization code
    DevChat API->>Google/GitHub API: Authorization code
    Google/GitHub API->>DevChat API: User email
    DevChat API->>DevChat Database: Find user with email
    DevChat Database->>DevChat API: Query response
    alt User Not Found
        DevChat API->>DevChat Database: Insert new user
        DevChat Database->>DevChat API: Query response
    end
    DevChat API->>DevChat Web: Access token
    DevChat Web->>User: Login completion