# This is a Github Actions CI template file
name: Workflow Name
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
env:
  REPO_ID: repo-id
  # GitOps API
  API_URI: https://api.github.com/repos/longlt201203/my-gitops/actions/workflows/105840951/dispatches
jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_ID }}:latest , ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_ID }}:${{ github.ref_name }}

  trigger-gitops-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Call dispatch workflow API
        run: |
          curl --location --request POST '${{ env.API_URI }}' \
          --header 'Authorization: Bearer ${{ secrets.PAT }}' \
          --header 'Content-Type: application/json' \
          --data '{"ref":"main","inputs":{"run_id":"${{ github.ref_name }}","project":"${{ env.REPO_ID }}"}}'
